const ACTIONS = {
    FETCH_GENRES_REQUEST: 'FETCH_GENRES_REQUEST',
    FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
    FETCH_GENRES_FAILURE: 'FETCH_GENRES_FAILURE',
    FETCH_POPULAR_REQUEST: 'FETCH_POPULAR_REQUEST',
    FETCH_POPULAR_SUCCESS: 'FETCH_POPULAR_SUCCESS',
    FETCH_POPULAR_FAILURE: 'FETCH_POPULAR_FAILURE',
    FETCH_IMAGES_REQUEST: 'FETCH_IMAGES_REQUEST',
    FETCH_IMAGES_SUCCESS: 'FETCH_IMAGES_SUCCESS',
    FETCH_IMAGES_FAILURE: 'FETCH_IMAGES_FAILURE'
};

export default ACTIONS;